
FROM golang:1.21



# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el código fuente al contenedor
COPY . .

# Compila la aplicación
RUN go build -o Main .

# Expone el puerto en el que se ejecutará la aplicación
EXPOSE 5051

# Ejecuta la aplicación al iniciar el contenedor
CMD ["./Main"]