# Use the official Golang image as a parent image
FROM golang:1.21

# Set the working directory inside the container
WORKDIR /app

# Copy the Go modules files and download the dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of your application source code
COPY . .

# Build your Go application
RUN go build -o main

# Expose the port that the application will run on
EXPOSE 3002

# Command to run the executable
CMD ["./main"]
