apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: proyecto2
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
  namespace: proyecto2
spec:

  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: maxwelltram/nodeserver:latest
        imagePullPolicy: Always
        name: servidor
        ports:
          - containerPort: 3001
        env:
          - name: DB_HOST
            value: "172.16.144.4"
          - name: DB_PORT
            value: "3306"
          - name: DB_USER
            value: "root"
          - name: DB_PASSWORD
            value: 'Olakeas123**'

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api
  namespace: proyecto2
spec:
  type: LoadBalancer
  ports:
    - name: api
      port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: api