apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: servicio-split
spec:
  service: service-traffic
  backends:
  - service: service-grpc
    weight: 50
  - service: service-pub-sub
    weight: 50