apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: proyecto2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grpc-server
  name: grpc-server
  namespace: proyecto2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
      - image: maxwelltram/grcpserver:latest
        imagePullPolicy: Always
        name: grpc-server
        ports:
          - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpc-server
  name: grpc-server
  namespace: proyecto2
spec:
  type: LoadBalancer
  ports:
    - name: grpc-server
      port: 3002
      protocol: TCP
      targetPort: 3002
  selector:
    app: grpc-server