# Use an official Node runtime as a parent image
FROM node:14-alpine

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install any needed packages specified in package.json
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose port 8000 for the Node.js application to listen on
EXPOSE 3001

# Start the Node.js application
CMD [ "node", "index.js" ]

# docker build --tag servidor .