apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: proyecto2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grpc-client
  name: grpc-client
  namespace: proyecto2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
      - image: maxwelltram/grcpcclient:latest
        imagePullPolicy: Always
        name: grpc-client
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpc-client
  name: grpc-client
  namespace: proyecto2
spec:
  type: LoadBalancer
  ports:
    - name: grpc-client
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: grpc-client